export enum Subjects {
  UserCreated = "user:created",
  UserUpdated = "user:updated",
  UserDeleted = "user:Deleted",
  ConversationCreated = "conversation:created",
  ConversationUpdated = "conversation:updated",
  ConversationDeleted = "conversation:deleted",
  ParticipantRemoved = "participant:removed",
  ParticipantsAdded = "participants:added",
  MessageCreated = "message:created",
  MessageUpdated = "message:updated",
  MessageDeleted = "message:deleted",
  UserConnectedToChat = "UserConnectedToChat",
  SendMessageToChat = "SendMessageToChat",
  ParticipantAddedToChat = "ParticipantAddedToChat",
  ParticipantRemovedFromChat = "ParticipantRemovedFromChat",
  MessgeSeen = "MessgeSeen",
  Typing = "Typing",
  StopTyping = "StopTyping",
  ConnectedUsers = "ConnectedUsers"
}
