apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: message
          image: prithwishdas60/message
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: chat
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URL
              value: 'mongodb://message-mongo-srv:27017'
            - name: DB_NAME
              value: 'message'
            - name: REDIS_HOST
              value: message-redis-srv
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: message-srv
spec:
  selector:
    app: message
  ports:
    - name: message
      protocol: TCP
      port: 3000
      targetPort: 3000